name: knoknok_mobile
description: "Reach out to those you love with a simple tap"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  dynamic_system_colors: ^1.8.0
  socket_io_client: ^3.0.2
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.1
  firebase_messaging: ^15.2.2
  firebase_core: ^3.11.0
  intl: ^0.20.2
  haptic_feedback: ^0.5.1+1
  bitsdojo_window: ^0.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
